# Generated by Django 3.0.2 on 2020-01-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20200104_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputlot',
            old_name='creatad_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='outputlot',
            old_name='creatad_at',
            new_name='created_at',
        ),
    ]
