# Generated by Django 3.0.2 on 2020-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='cnpj',
            field=models.IntegerField(unique=True),
        ),
    ]
